In [2]:
import numpy as np

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
data = np.random.randint(0,100,(10,2))

In [9]:
data

array([[66, 59],
       [54, 61],
       [88, 82],
       [33, 31],
       [18, 99],
       [41, 75],
       [62,  0],
       [97, 65],
       [49, 32],
       [79, 20]])

In [10]:
scaler_model = MinMaxScaler()

In [11]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [12]:
scaler_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [13]:
scaler_model.transform(data)

array([[0.60759494, 0.5959596 ],
       [0.4556962 , 0.61616162],
       [0.88607595, 0.82828283],
       [0.18987342, 0.31313131],
       [0.        , 1.        ],
       [0.29113924, 0.75757576],
       [0.55696203, 0.        ],
       [1.        , 0.65656566],
       [0.39240506, 0.32323232],
       [0.7721519 , 0.2020202 ]])

In [14]:
scaler_model.fit_transform(data)

array([[0.60759494, 0.5959596 ],
       [0.4556962 , 0.61616162],
       [0.88607595, 0.82828283],
       [0.18987342, 0.31313131],
       [0.        , 1.        ],
       [0.29113924, 0.75757576],
       [0.55696203, 0.        ],
       [1.        , 0.65656566],
       [0.39240506, 0.32323232],
       [0.7721519 , 0.2020202 ]])

In [16]:
import pandas as pd

In [18]:
my_data = np.random.randint(0,101,(50,4))

In [19]:
my_data

array([[34, 56, 42, 91],
       [32, 74, 85, 70],
       [10,  1, 39, 59],
       [76,  1, 45, 76],
       [61, 21, 38, 68],
       [ 4, 69, 36, 40],
       [92,  6, 66, 37],
       [78, 79, 50, 89],
       [43, 15, 69, 38],
       [83, 50, 41, 74],
       [97, 59, 32, 23],
       [12, 74, 86, 26],
       [ 4, 85, 40, 59],
       [73, 52, 91, 67],
       [32, 33, 33, 97],
       [87, 11, 43, 37],
       [83, 97, 99, 24],
       [32, 54, 97, 79],
       [ 2, 85, 31, 94],
       [81, 78, 67, 88],
       [76, 46, 16, 43],
       [57,  5, 76, 42],
       [31, 39,  8, 88],
       [29, 87,  2, 47],
       [25, 51, 57,  9],
       [81,  9, 14,  1],
       [75,  9, 82, 93],
       [79, 13, 91,  2],
       [69, 77, 68, 64],
       [71, 63, 91, 58],
       [ 2, 44, 76, 12],
       [40, 18, 10, 12],
       [53, 96, 72, 95],
       [93, 59, 93, 50],
       [80, 58, 33, 52],
       [ 4, 60, 91, 20],
       [95, 58, 96,  5],
       [99, 31, 64, 81],
       [67,  7, 59,  9],
       [67, 20, 86, 76],


In [23]:
df = pd.DataFrame(data = my_data, columns = ['f1','f2','f3','label'])

In [24]:
df

f1  f2  f3  label
0   34  56  42     91
1   32  74  85     70
2   10   1  39     59
3   76   1  45     76
4   61  21  38     68
5    4  69  36     40
6   92   6  66     37
7   78  79  50     89
8   43  15  69     38
9   83  50  41     74
10  97  59  32     23
11  12  74  86     26
12   4  85  40     59
13  73  52  91     67
14  32  33  33     97
15  87  11  43     37
16  83  97  99     24
17  32  54  97     79
18   2  85  31     94
19  81  78  67     88
20  76  46  16     43
21  57   5  76     42
22  31  39   8     88
23  29  87   2     47
24  25  51  57      9
25  81   9  14      1
26  75   9  82     93
27  79  13  91      2
28  69  77  68     64
29  71  63  91     58
30   2  44  76     12
31  40  18  10     12
32  53  96  72     95
33  93  59  93     50
34  80  58  33     52
35   4  60  91     20
36  95  58  96      5
37  99  31  64     81
38  67   7  59      9
39  67  20  86     76
40  60  39  30     34
41  98  64  64      2
42  29  98  37     50
43  61  94  97     22
44  83  17  57     22
45  55  59  56      4
46  38  88  51     73
47  61   9  55     48
48   9  66  52     22
49   8  36  11     39

In [32]:
X = df[['f1','f2','f3']]

In [33]:
y = df['label']

In [34]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 101)

In [39]:
X_train.shape

(35, 3)

In [41]:
X_test.shape

(15, 3)