In [2]:
import torch
import numpy as np

In [4]:
x = torch.arange(6).reshape(3,2)

In [6]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [9]:
type(x[1,1])

torch.Tensor

In [11]:
x[:,1]

tensor([1, 3, 5])

In [13]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [15]:
x = torch.arange(10)

In [17]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x = x.reshape(2,5)

In [29]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
x = torch.arange(10)

In [33]:
x.shape

torch.Size([10])

In [35]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [37]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
z = x.view(2,5)

In [42]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [44]:
x[0] = 9999

In [46]:
x

tensor([[9999, 9999, 9999, 9999, 9999],
        [   5,    6,    7,    8,    9]])

In [48]:
z

tensor([[9999, 9999, 9999, 9999, 9999],
        [   5,    6,    7,    8,    9]])

In [50]:
x = torch.arange(10)

In [52]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x.shape

torch.Size([10])

In [57]:
#INFER what the 2nd dimension
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [59]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])