In [2]:
import torch

In [4]:
import numpy as np

In [6]:
torch.__version__

'1.1.0'

In [8]:
arr = np.array([1,2,3,4,5])

In [10]:
print(arr)

[1 2 3 4 5]


In [12]:
arr.dtype

dtype('int64')

In [14]:
type(arr)

numpy.ndarray

In [16]:
x = torch.from_numpy(arr)

In [18]:
type(x)

torch.Tensor

In [20]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [22]:
x.dtype

torch.int64

In [24]:
arr2d  = np.arange(0.0,12.0)

In [26]:
arr2d = arr2d.reshape(4,3)

In [28]:
x2 = torch.from_numpy(arr2d)

In [29]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [31]:
arr

array([1, 2, 3, 4, 5])

In [33]:
x

tensor([1, 2, 3, 4, 5])

In [35]:
arr[0] = 99

In [37]:
arr

array([99,  2,  3,  4,  5])

In [39]:
x

tensor([99,  2,  3,  4,  5])

In [41]:
my_arr = np.arange(0,10)

In [43]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
my_tensor = torch.tensor(my_arr)

In [47]:
my_other_tensor = torch.from_numpy(my_arr)

In [49]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
my_arr[0] = 88888

In [55]:
my_arr

array([88888,     1,     2,     3,     4,     5,     6,     7,     8,
           9])

In [57]:
my_other_tensor

tensor([88888,     1,     2,     3,     4,     5,     6,     7,     8,     9])

In [59]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
new_arr = np.array([1,2,3])

In [62]:
new_arr.dtype

dtype('int64')

In [64]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [68]:
my_tensor = torch.Tensor(new_arr)

In [70]:
my_tensor.dtype

torch.float32

In [75]:
torch.empty(2,2)

tensor([[ 0.0000e+00, -2.5244e-29],
        [-8.1303e+10, -2.5250e-29]])

In [79]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [81]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [85]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [87]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [89]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [90]:
my_tensor = torch.tensor([1,2,3])

In [92]:
my_tensor.dtype

torch.int64

In [98]:
my_tensor = my_tensor.type(torch.int32)

In [100]:
my_tensor.dtype

torch.int32

In [102]:
torch.rand(4,3)

tensor([[0.6929, 0.9811, 0.8987],
        [0.5947, 0.0900, 0.1123],
        [0.5934, 0.1258, 0.2907],
        [0.1642, 0.9388, 0.3752]])

In [104]:
torch.randn(4,3)

tensor([[ 0.8774, -0.3047, -0.5508],
        [-0.0817,  0.7719, -1.4565],
        [ 0.0343, -1.1952,  0.5311],
        [-0.6017,  0.6145,  1.2946]])

In [107]:
torch.randint(low=0,high=11,size=(5,5))

tensor([[ 0,  5,  0,  1, 10],
        [ 9,  0,  4,  1,  0],
        [ 7,  3,  5,  2,  6],
        [ 4,  7,  1,  3,  8],
        [ 3,  2,  9,  2,  1]])

In [109]:
x = torch.zeros(2,5)

In [111]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [113]:
x.shape

torch.Size([2, 5])

In [115]:
torch.rand_like(x)

tensor([[0.0070, 0.6176, 0.7203, 0.1144, 0.7160],
        [0.4954, 0.4919, 0.7630, 0.0206, 0.1370]])

In [117]:
torch.randn_like(x)

tensor([[ 0.0224, -0.2473,  0.1995,  0.9574, -0.0410],
        [ 0.1517, -1.2691, -0.9541, -0.8640,  0.1794]])

In [119]:
torch.randint_like(x,low=0,high=11)

tensor([[ 9., 10.,  9.,  0.,  5.],
        [ 5.,  8.,  2.,  9.,  4.]])

In [122]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])